/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PhemiumPush {
    'active': boolean;
    'appId': string;
    'firebaseConfig': any;
    'initialize': () => Promise<void>;
    'phemiumConfig': any;
    'showPushInstances': () => Promise<void>;
    'token': string;
  }
}

declare global {


  interface HTMLPhemiumPushElement extends Components.PhemiumPush, HTMLStencilElement {}
  var HTMLPhemiumPushElement: {
    prototype: HTMLPhemiumPushElement;
    new (): HTMLPhemiumPushElement;
  };
  interface HTMLElementTagNameMap {
    'phemium-push': HTMLPhemiumPushElement;
  }
}

declare namespace LocalJSX {
  interface PhemiumPush extends JSXBase.HTMLAttributes<HTMLPhemiumPushElement> {
    'active'?: boolean;
    'appId'?: string;
    'firebaseConfig'?: any;
    'phemiumConfig'?: any;
    'token'?: string;
  }

  interface IntrinsicElements {
    'phemium-push': PhemiumPush;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


